<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InternshipsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $internships = [
            [
                'title' => 'Software Engineering Intern',
                'company' => 'TechCorp',
                'location' => 'New York, NY',
                'date' => '2025-06-01',
                'domain' => 'Informatique',
                'description' => 'Develop and test software applications.',
                'applies' => 50,
                'link' => 'https://example.com/internship1',
                'paid' => true,
                'duration' => '3 months',
                'type' => 'Full-time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Marketing Intern',
                'company' => 'MarketGenius',
                'location' => 'Los Angeles, CA',
                'date' => '2025-07-15',
                'domain' => 'Marketing',
                'description' => 'Assist in marketing campaigns and strategies.',
                'applies' => 30,
                'link' => 'https://example.com/internship2',
                'paid' => false,
                'duration' => '6 months',
                'type' => 'Part-time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Data Analyst Intern',
                'company' => 'DataWorks',
                'location' => 'Chicago, IL',
                'date' => '2025-08-01',
                'domain' => 'Finance',
                'description' => 'Analyze financial data and trends.',
                'applies' => 40,
                'link' => 'https://example.com/internship3',
                'paid' => true,
                'duration' => '4 months',
                'type' => 'Full-time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Graphic Design Intern',
                'company' => 'CreativeStudio',
                'location' => 'San Francisco, CA',
                'date' => '2025-09-10',
                'domain' => 'Marketing',
                'description' => 'Create visual content for marketing.',
                'applies' => 25,
                'link' => 'https://example.com/internship4',
                'paid' => false,
                'duration' => '5 months',
                'type' => 'Part-time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'HR Intern',
                'company' => 'PeopleFirst',
                'location' => 'Houston, TX',
                'date' => '2025-10-05',
                'domain' => 'Gestion',
                'description' => 'Assist in HR management and recruitment.',
                'applies' => 35,
                'link' => 'https://example.com/internship5',
                'paid' => true,
                'duration' => '6 months',
                'type' => 'Full-time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cybersecurity Intern',
                'company' => 'SecureNet',
                'location' => 'Austin, TX',
                'date' => '2025-11-12',
                'domain' => 'Informatique',
                'description' => 'Work on cybersecurity protocols.',
                'applies' => 20,
                'link' => 'https://example.com/internship6',
                'paid' => true,
                'duration' => '3 months',
                'type' => 'Full-time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Electrical Engineering Intern',
                'company' => 'ElectroTech',
                'location' => 'Seattle, WA',
                'date' => '2025-12-01',
                'domain' => 'Électronique',
                'description' => 'Design and test electronic circuits.',
                'applies' => 45,
                'link' => 'https://example.com/internship7',
                'paid' => true,
                'duration' => '4 months',
                'type' => 'Full-time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Business Analyst Intern',
                'company' => 'BizConsult',
                'location' => 'Boston, MA',
                'date' => '2025-07-20',
                'domain' => 'Finance',
                'description' => 'Assist in business process analysis.',
                'applies' => 28,
                'link' => 'https://example.com/internship8',
                'paid' => false,
                'duration' => '5 months',
                'type' => 'Part-time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'AI Research Intern',
                'company' => 'AI Labs',
                'location' => 'San Diego, CA',
                'date' => '2025-08-15',
                'domain' => 'Informatique',
                'description' => 'Research artificial intelligence models.',
                'applies' => 15,
                'link' => 'https://example.com/internship9',
                'paid' => true,
                'duration' => '6 months',
                'type' => 'Full-time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Supply Chain Intern',
                'company' => 'LogistiCo',
                'location' => 'Miami, FL',
                'date' => '2025-09-05',
                'domain' => 'Gestion',
                'description' => 'Manage and optimize supply chain operations.',
                'applies' => 33,
                'link' => 'https://example.com/internship10',
                'paid' => true,
                'duration' => '4 months',
                'type' => 'Full-time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('internships')->insert($internships);
    }
}
